# Generated by Django 2.2.2 on 2021-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.CharField(max_length=10000, verbose_name='Город'),
        ),
    ]
