# Generated by Django 2.2.2 on 2021-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=255)),
                ('city_to', models.CharField(max_length=255)),
                ('from_address', models.BooleanField(default=False)),
                ('to_address', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('payer', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('fence_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('fence_date', models.CharField(max_length=255)),
                ('fence_interval', models.CharField(max_length=255)),
                ('quantity_places', models.CharField(max_length=255)),
                ('quantity_weight', models.CharField(max_length=255)),
                ('quantity_volume', models.CharField(max_length=255)),
                ('delivery_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Принято', 'ПРИНЯТО'), ('Ожидается забор груза', 'ОЖИДАЕТСЯ ЗАБОР ГРУЗА'), ('Ожидается доставка груза', 'ОЖИДАЕТСЯ ДОСТАВКА ГРУЗА'), ('Принято на склад отправки', 'ПРИНЯТО НА СКЛАД ОТПРАВКИ'), ('Ожидается отправка', 'ОЖИДАЕТСЯ ОТПРАВКА'), ('В пути', 'В ПУТИ'), ('В пути до терминала', 'В ПУТИ'), ('Доставка другой транспортной компанией', 'В ПУТИ'), ('Прибыло на склад получения', 'ПРИБЫЛО НА СКЛАД ПОЛУЧЕНИЯ'), ('Готово к выдаче', 'ГОТОВО К ВЫДАЧЕ'), ('Выдано', 'ВЫДАНО'), ('Прибыло на склад транзита', 'ПРИБЫЛО НА СКЛАД ТРАНЗИТА')], default='Уточняется', max_length=50)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatusConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('tracking_number_client', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Принято', 'ПРИНЯТО'), ('Ожидается забор груза', 'ОЖИДАЕТСЯ ЗАБОР ГРУЗА'), ('Ожидается доставка груза', 'ОЖИДАЕТСЯ ДОСТАВКА ГРУЗА'), ('Принято на склад отправки', 'ПРИНЯТО НА СКЛАД ОТПРАВКИ'), ('Ожидается отправка', 'ОЖИДАЕТСЯ ОТПРАВКА'), ('В пути', 'В ПУТИ'), ('В пути до терминала', 'В ПУТИ'), ('Доставка другой транспортной компанией', 'В ПУТИ'), ('Прибыло на склад получения', 'ПРИБЫЛО НА СКЛАД ПОЛУЧЕНИЯ'), ('Готово к выдаче', 'ГОТОВО К ВЫДАЧЕ'), ('Выдано', 'ВЫДАНО'), ('Прибыло на склад транзита', 'ПРИБЫЛО НА СКЛАД ТРАНЗИТА')], default='Уточняется', max_length=50)),
                ('delivery_date', models.DateField()),
                ('status_pay', models.CharField(choices=[('Оплачено', 'ОПЛАЧЕНО'), ('Не оплачено', 'НЕ ОПЛАЧЕНО')], default='Уточняется', max_length=50)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
