# Generated by Django 2.2.2 on 2021-06-15 13:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_to', models.CharField(max_length=255, unique=True, verbose_name='Откуда')),
                ('city_from', models.CharField(max_length=255, unique=True, verbose_name='Куда')),
                ('address_from', models.CharField(max_length=255, verbose_name='Адрес')),
                ('terminal_from', models.CharField(max_length=255, verbose_name='Терминал')),
                ('address_to', models.CharField(max_length=255, verbose_name='Адрес')),
                ('terminal_to', models.CharField(max_length=255, verbose_name='Терминал')),
                ('date_cargo', models.DateTimeField(verbose_name='Дата забора груза')),
                ('type_transporation', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Экспресс', 'Экспресс'), ('Конверт', 'Конверт')], default='Стандарт', max_length=50, verbose_name='Вид перевозки')),
                ('nature_cargo', models.CharField(max_length=255, verbose_name='Характер груза')),
                ('declared_value', models.CharField(default='', max_length=255, verbose_name='Объявленная стоимость')),
                ('insurance', models.BooleanField(default=False, verbose_name='Страховка')),
                ('return_of_accompanying_documents', models.BooleanField(default=False, verbose_name='Возврат сопроводительных документов')),
                ('sending_accompanying_documents', models.BooleanField(default=False, verbose_name='Отправка сопроводительных документов')),
                ('loading_and_unloading_sender', models.BooleanField(default=False, verbose_name='Погрузо-разгрузочные работы у отправителя')),
                ('loading_and_unloading_recipient', models.BooleanField(default=False, verbose_name='Погрузо-разгрузочные работы у получателя')),
                ('pass_sender_territory', models.BooleanField(default=False, verbose_name='Пропуск на территорию отправителя')),
                ('registration_for_shipment', models.BooleanField(default=False, verbose_name='Запись на отгрузку')),
                ('paid_entry_sender_territory', models.BooleanField(default=False, verbose_name='Платный въезд на территорию отправителя')),
                ('internal_shipment_number', models.BooleanField(default=False, verbose_name='Внутренний номер отгрузки')),
                ('cod', models.BooleanField(default=False, verbose_name='Наложенный платеж')),
                ('second_address', models.BooleanField(default=False, verbose_name='Заезд на второй адрес')),
                ('delivery_confirmation', models.BooleanField(default=False, verbose_name='Подтверждение доставки')),
                ('power_of_attorney', models.BooleanField(default=False, verbose_name='Доверенность')),
                ('pre_call', models.BooleanField(default=False, verbose_name='Предварительный звонок')),
                ('rigid_packaging', models.BooleanField(default=False, verbose_name='Жесткая упаковка')),
                ('pallet_board', models.BooleanField(default=False, verbose_name='Паллетный борт')),
                ('bag', models.BooleanField(default=False, verbose_name='Мешок')),
                ('cardboard_box', models.BooleanField(default=False, verbose_name='Картонная коробка')),
                ('pallet', models.BooleanField(default=False, verbose_name='Палет')),
                ('strapping', models.BooleanField(default=False, verbose_name='Стреппинг')),
                ('stretch', models.BooleanField(default=False, verbose_name='Стрейч - пленка')),
                ('air_bubble', models.BooleanField(default=False, verbose_name='Воздушно - пузырьковая пленка')),
                ('fio_individual', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('passport_individual', models.IntegerField(default='', max_length=255, verbose_name='Серия и номер паспорта')),
                ('email_individual', models.EmailField(default='', max_length=255, verbose_name='Email')),
                ('phone_individual', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='Контактный телефон')),
                ('fio_entity', models.CharField(default='', max_length=255, verbose_name='Название компании')),
                ('inn_entity', models.IntegerField(default='', max_length=255, verbose_name='ИНН')),
                ('contact_person_entity', models.CharField(default='', max_length=255, verbose_name='Контактное лицо')),
                ('email_entity', models.EmailField(default='', max_length=255, verbose_name='Email')),
                ('phone_entity', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='Контактный телефон')),
                ('pay_cargo', models.CharField(choices=[('Наличный расчет', 'Наличный расчет'), ('Безналичный расчет', 'Безналичный расчет')], default='Наличный расчет', max_length=50, verbose_name='Форма оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Принято', 'ПРИНЯТО'), ('Ожидается забор груза', 'ОЖИДАЕТСЯ ЗАБОР ГРУЗА'), ('Ожидается доставка груза', 'ОЖИДАЕТСЯ ДОСТАВКА ГРУЗА'), ('Принято на склад отправки', 'ПРИНЯТО НА СКЛАД ОТПРАВКИ'), ('Ожидается отправка', 'ОЖИДАЕТСЯ ОТПРАВКА'), ('В пути', 'В ПУТИ'), ('В пути до терминала', 'В ПУТИ'), ('Доставка другой транспортной компанией', 'В ПУТИ'), ('Прибыло на склад получения', 'ПРИБЫЛО НА СКЛАД ПОЛУЧЕНИЯ'), ('Готово к выдаче', 'ГОТОВО К ВЫДАЧЕ'), ('Выдано', 'ВЫДАНО'), ('Прибыло на склад транзита', 'ПРИБЫЛО НА СКЛАД ТРАНЗИТА')], default='Уточняется', max_length=50)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatusConsignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('tracking_number_client', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Принято', 'ПРИНЯТО'), ('Ожидается забор груза', 'ОЖИДАЕТСЯ ЗАБОР ГРУЗА'), ('Ожидается доставка груза', 'ОЖИДАЕТСЯ ДОСТАВКА ГРУЗА'), ('Принято на склад отправки', 'ПРИНЯТО НА СКЛАД ОТПРАВКИ'), ('Ожидается отправка', 'ОЖИДАЕТСЯ ОТПРАВКА'), ('В пути', 'В ПУТИ'), ('В пути до терминала', 'В ПУТИ'), ('Доставка другой транспортной компанией', 'В ПУТИ'), ('Прибыло на склад получения', 'ПРИБЫЛО НА СКЛАД ПОЛУЧЕНИЯ'), ('Готово к выдаче', 'ГОТОВО К ВЫДАЧЕ'), ('Выдано', 'ВЫДАНО'), ('Прибыло на склад транзита', 'ПРИБЫЛО НА СКЛАД ТРАНЗИТА')], default='Уточняется', max_length=50)),
                ('delivery_date', models.DateField()),
                ('status_pay', models.CharField(choices=[('Оплачено', 'ОПЛАЧЕНО'), ('Не оплачено', 'НЕ ОПЛАЧЕНО')], default='Уточняется', max_length=50)),
                ('route', models.CharField(max_length=255)),
            ],
        ),
    ]
