# Generated by Django 2.2.2 on 2021-06-22 11:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='contact_person_entity',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_entity',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='email_individual',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='fio_entity',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='fio_individual',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='inn_entity',
            field=models.IntegerField(blank=True, default='', max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual',
            field=models.IntegerField(blank=True, default='', max_length=10, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='phone_entity',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, unique=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='phone_individual',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, unique=True, verbose_name='Контактный телефон'),
        ),
    ]
