# Generated by Django 2.2.2 on 2021-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='recipient_customer',
            field=models.BooleanField(default=False, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='recipient_payer',
            field=models.BooleanField(default=False, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='sender_customer',
            field=models.BooleanField(default=False, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='sender_payer',
            field=models.BooleanField(default=False, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='third_person_customer',
            field=models.BooleanField(default=False, verbose_name='Третье лицо'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='third_person_payer',
            field=models.BooleanField(default=False, verbose_name='Третье лицо'),
        ),
    ]
