# Generated by Django 2.2.2 on 2021-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_auto_20210615_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='interval',
            field=models.CharField(default='9:00 - 18:00', max_length=50, verbose_name='Интервал доставки'),
        ),
    ]
