# Generated by Django 2.2.2 on 2021-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_auto_20210629_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='pay_cargo',
            field=models.CharField(choices=[('Наличный расчет', 'Наличный расчет'), ('Безналичный расчет', 'Безналичный расчет'), ('Карта', 'Карта')], max_length=50, verbose_name='Форма оплаты'),
        ),
    ]
