# Generated by Django 2.2.2 on 2021-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_auto_20210629_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='height_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='length_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_hardest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Самое тяжелое(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_highest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Самое высокое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_longest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Самое длинное(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общий объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общий вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_widest',
            field=models.IntegerField(blank=True, null=True, verbose_name='Самое широкое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='volume_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='weight_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='width_one',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина(м)'),
        ),
    ]
