# Generated by Django 2.2.2 on 2021-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0004_auto_20210615_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='third_person',
            field=models.CharField(default='', max_length=300, verbose_name='Город, имя, телефон'),
        ),
    ]
