# Generated by Django 2.2.2 on 2021-06-29 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0005_auto_20210629_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объявленная стоимость'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='document_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Высота(см)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='document_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Длина(см)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='document_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='document_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Ширина(см)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='height_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='length_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='place_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_hardest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Самое тяжелое(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_highest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Самое высокое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_longest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Самое длинное(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_place_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общий объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общий вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='some_widest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Самое широкое(м)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='volume_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объем(м3)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='weight_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес(кг)'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='width_one',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ширина(м)'),
        ),
    ]
