# Generated by Django 2.2.2 on 2021-06-16 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0005_orderconsignment_third_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='document_height',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='document_length',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='document_weight',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='document_width',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='height_one',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='length_one',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='place_quantity',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_hardest',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_highest',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_longest',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_place_quantity',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_volume',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_weight',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='some_widest',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='volume_one',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='weight_one',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='width_one',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='declared_value',
            field=models.PositiveIntegerField(default='', max_length=255, verbose_name='Объявленная стоимость'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='inn_entity',
            field=models.PositiveIntegerField(default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual',
            field=models.PositiveIntegerField(default='', max_length=10, verbose_name='Серия и номер паспорта'),
        ),
    ]
