# Generated by Django 2.2.2 on 2021-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0008_auto_20210630_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='height_one',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.1', max_digits=5, null=True, verbose_name='Высота(м)*'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='length_one',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.1', max_digits=5, null=True, verbose_name='Длина(м)*'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='volume_one',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.1', max_digits=5, null=True, verbose_name='Объем(м3)*'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='width_one',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.1', max_digits=5, null=True, verbose_name='Ширина(м)*'),
        ),
    ]
