# Generated by Django 2.2.24 on 2021-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0009_auto_20210630_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='carry_recipient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='carry_sender',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Пронос(м)'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='cod_input',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сумма наложенного платежа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='floor_recipient',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поднятие(этаж)'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='floor_sender',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поднятие(этаж)'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='service_lift_recipient',
            field=models.BooleanField(default='', verbose_name='Наличие грузового лифта'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='service_lift_sender',
            field=models.BooleanField(default='', verbose_name='Наличие грузового лифта'),
        ),
    ]
