# Generated by Django 2.2.24 on 2021-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0010_auto_20210701_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='documents',
            field=models.CharField(choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='', max_length=50, verbose_name='Выберите тип документа'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='driver_license_individual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер водительского удостоверения*'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='international_passport_individual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Серия и номер загранпаспорта*'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='military_ID_individual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер военного билета*'),
        ),
    ]
