# Generated by Django 2.2.24 on 2021-07-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0012_auto_20210702_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderconsignment',
            old_name='passport_individual',
            new_name='doc_individual',
        ),
        migrations.RemoveField(
            model_name='orderconsignment',
            name='driver_license_individual',
        ),
        migrations.RemoveField(
            model_name='orderconsignment',
            name='international_passport_individual',
        ),
        migrations.RemoveField(
            model_name='orderconsignment',
            name='military_ID_individual',
        ),
    ]
