# Generated by Django 2.2.24 on 2021-07-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0013_auto_20210702_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderconsignment',
            old_name='doc_individual',
            new_name='passport_individual',
        ),
    ]
