# Generated by Django 2.2.24 on 2021-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0015_auto_20210702_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='documents',
            field=models.CharField(blank=True, choices=[('Паспорт', 'Паспорт'), ('Заграничный паспорт', 'Заграничный паспорт'), ('Военный билет', 'Военный билет'), ('Водительское удостоверение', 'Водительское удостоверение')], default='', max_length=50, null=True, verbose_name='Выберите тип документа*'),
        ),
        migrations.AlterField(
            model_name='orderconsignment',
            name='passport_individual',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Серия и номер выбранного документа*'),
        ),
    ]
