# Generated by Django 2.2.24 on 2021-07-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0017_auto_20210705_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconsignment',
            name='third_person_customer',
        ),
        migrations.RemoveField(
            model_name='orderconsignment',
            name='third_person_payer',
        ),
    ]
