# Generated by Django 2.2.24 on 2021-07-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0018_auto_20210705_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='callback_one_hour',
            field=models.BooleanField(default='', verbose_name='Отзвон за 1 час'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='callback_two_hour',
            field=models.BooleanField(default='', verbose_name='Отзвон за 2 час'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='check_second_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город и адрес'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='info_internal_shipment_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='info_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='order_per_day',
            field=models.BooleanField(default='', verbose_name='Заказать за сутки'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='order_per_hour',
            field=models.BooleanField(default='', verbose_name='Заказать за час'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='reimbursement_method',
            field=models.CharField(blank=True, choices=[('По чеку на адресе', 'По чеку на адресе'), ('Включить в счет', 'Включить в счет')], default='', max_length=50, null=True, verbose_name='Способ возмещения суммы'),
        ),
        migrations.AddField(
            model_name='orderconsignment',
            name='sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сумма'),
        ),
    ]
