# Generated by Django 2.2.24 on 2021-07-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0019_auto_20210720_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='type_transporation',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Экспресс', 'Экспресс'), ('Конверт', 'Конверт')], default='Стандарт', max_length=50, verbose_name='Вид перевозки'),
        ),
    ]
