# Generated by Django 2.2.24 on 2021-07-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0021_auto_20210720_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconsignment',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Комментарий'),
        ),
    ]
