# Generated by Django 2.2.24 on 2021-07-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0022_orderconsignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconsignment',
            name='interval',
            field=models.CharField(choices=[('9:00 - 18:00', '9:00 - 18:00'), ('12:00 - 21:00', '12:00 - 21:00'), ('15:00 - 00:00', '15:00 - 00:00')], default='9:00 - 18:00', max_length=50, verbose_name='Интервал доставки'),
        ),
    ]
