# Generated by Django 2.2.2 on 2021-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityto', models.CharField(max_length=255)),
                ('cityfrom', models.CharField(max_length=255)),
                ('term_standart_to', models.CharField(max_length=255)),
                ('term_standart_from', models.CharField(max_length=255)),
                ('term_express_to', models.CharField(max_length=255)),
                ('term_express_from', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='calculate',
            name='weightfrom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calculate',
            name='weightto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
